### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/LaborUnion#2]
- [x] favicon
- [x] helmet info (目前直接寫死，有第二頁之後再用 `react-helmet` 
- [ ] google analytic
- [x] links 
- [x] photos
- [x] google form
- [x] pre-render
- [ ] 修法整理表格

**Comment by mark86092** [comment]
看到一下可以做的 [Prerender to static html](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#pre-rendering-into-static-html-files)

用這個可以產生 prerender 的 index.html （假裝是 SSR 的過程），方便搜尋引擎爬 helmet、文字等結構

（我有空會看一下內文提到的 react-snapshot 這個模組）

**Comment by barry800414** [comment]
@mark86092 
可以跟我說如果要綁定 github 的頁面到網域底下，我還要做什麼嗎？
網域：`https://labor-union.goodjob.life`

prerender 我會再來試

**Comment by barry800414** [comment]
關於 google analytics tracking 
https://developers.google.com/analytics/devguides/collection/analyticsjs/creating-trackers
https://developers.google.com/analytics/devguides/collection/analyticsjs/cookies-user-id#automatic_cookie_domain_configuration

看完了以上文章，目前我看 [react-ga 的設定](https://github.com/react-ga/react-ga/blob/master/src/index.js#L65)已經是 'auto' ，所以 cookie 應該是可以在 goodjob.life 間 share，不過如果用一個追蹤 ID (UA-xxxxxxx-1）塞 analytics.js 在 labor-union.goodjob.life 網域到底能不能追蹤，我還是不太確定說。

另外又看到一篇：
https://www.lunametrics.com/blog/2016/08/11/subdomain-tracking-google-analytics/
這個要設定嗎？

看有沒有空線上討論一下

**Comment by mark86092** [comment]
關於 ga 

![image](https://user-images.githubusercontent.com/1908007/33510805-edcd7a4a-d74b-11e7-8f62-eb7c43d5e5ee.png)

上圖是從 Google Analysis 的導覽匡擷取出來的圖

我的問題是，跟本來的站台 share 同個 ID（即 Properties & App 上面的代號），這樣做的目的是什麼？

**Comment by mark86092** [comment]
> 要綁定 github 的頁面到網域底下，我還要做什麼嗎？

1. 在 gh-pages branch 加上 CNAME 純文字檔，內容是

```
labor-union.goodjob.life
```

由於我們網站會自動 build，換句話說，要在 master 分支的 public 資料夾加上 CNAME 純文字檔

2. 處理 domain：將 labor-union.goodjob.life 透過 cname 的方法指到 goodjoblife.github.io

這段我要從 cloudflare 設定

3. 處理 http 轉址至 https，當使用者造訪 http 版本的時候，要重新導向至 https 版本
